# Generated by Django 4.1.5 on 2023-01-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(verbose_name='Mobile Number')),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.FileField(blank=True, null=True, upload_to='singer/')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Song Name')),
                ('release_date', models.DateField()),
                ('singer', models.ManyToManyField(related_name='song', to='quickstart.singer')),
            ],
        ),
    ]
